name: Cypress Tests

on: push
env:
  CLOUNDINARY_API: ${{ secrets.CLOUNDINARY_API }}
  FORM_EMAIL: ${{ secrets.FORM_EMAIL}}
  FORM_EMAIL_PASSWORD: ${{ secrets.FORM_EMAIL_PASSWORD}}
  FORM_EMAIL_PROVIDER: ${{ secrets.FORM_EMAIL_PROVIDER}}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID}}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET}}
  GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN}}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET}}
  NEXTAUTH_URL:  ${{ secrets.NEXTAUTH_URL}}
  NEXT_PUBLIC_CLOUNDINARY_API: ${{ secrets. NEXT_PUBLIC_CLOUNDINARY_API}}
  POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL}}
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
